# Generated by Django 2.0 on 2020-11-23 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.CharField(max_length=255)),
                ('attendance_marked', models.BooleanField(default=False)),
                ('late_mark', models.BooleanField(default=False)),
                ('half_day', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_time', models.TimeField(null=True)),
                ('attendance_time', models.TimeField(null=True)),
                ('no_late_marks', models.TimeField(null=True)),
                ('half_day_time', models.TimeField(null=True)),
                ('checkout_time', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.CharField(max_length=255)),
                ('checkout_marked', models.BooleanField(default=False)),
                ('early_mark', models.BooleanField(default=False)),
                ('half_day', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('face_image1', models.ImageField(max_length=255, upload_to='')),
                ('face_image2', models.ImageField(max_length=255, upload_to='')),
                ('face_image3', models.ImageField(max_length=255, upload_to='')),
                ('details', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
