# Generated by Django 2.0 on 2020-11-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='face_image1',
            field=models.ImageField(max_length=255, upload_to='media/uploaded_images'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='face_image2',
            field=models.ImageField(blank=True, max_length=255, upload_to='media/uploaded_images'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='face_image3',
            field=models.ImageField(blank=True, max_length=255, upload_to='media/uploaded_images'),
        ),
    ]
