# Generated by Django 2.0 on 2020-11-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201123_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesetting',
            name='attendance_time',
            field=models.CharField(help_text='In Am', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendancesetting',
            name='checkout_time',
            field=models.CharField(help_text='In Am', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendancesetting',
            name='college_time',
            field=models.CharField(help_text='In Am', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendancesetting',
            name='half_day_time',
            field=models.CharField(help_text='In Am', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendancesetting',
            name='no_late_marks',
            field=models.CharField(help_text='In Am', max_length=255, null=True),
        ),
    ]
