# Generated by Django 2.0 on 2020-11-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201124_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesetting',
            name='checkout_time',
            field=models.CharField(help_text='In Pm', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendancesetting',
            name='no_late_marks',
            field=models.IntegerField(null=True),
        ),
    ]
