# Generated by Django 2.0 on 2020-11-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201124_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='image_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendancesetting',
            name='no_late_marks',
            field=models.IntegerField(help_text='After which Absentee will be marked', null=True),
        ),
    ]
