# Generated by Django 2.0 on 2020-11-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201124_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='checkout_marked',
            new_name='attendance_marked',
        ),
        migrations.AddField(
            model_name='checkout',
            name='image_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
